# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMyPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestMyPod
  pod 'ModesoNavigationTabs', :git => 'https://github.com/Modeso/ModesoNavigationTabs.git'
end
